### ISSUE TITLE
How to make loopback audio source to a streaming AudioClip?

### ISSUE THREAD

**Issue by kuochiyoug** [hallidev/UnityWASAPILoopbackAudio#2]
Hi! I am looking for the fast solution to make a audio clip which is always listen to the loopback.
I saw your program seems work very well to capture audio data and draw the spectrum realtime.

Is it possible to render the loopback audio to a audio clip realtime?

**Comment by hallidev** [comment]
It’s definitely possible but I haven’t worked much with Unity’s AudioClip. You could use this repo as a starting point along with the CSCore samples here: https://github.com/filoe/cscore/tree/master/Samples

I think what you’d need to do is capture the raw incoming bytes (which I’m doing in RealtimeAudio.cs) and load them into an AudioClip. 

I’m no audio pro though and it can get complicated with sound formats, etc. It'll take some tinkering but I’m sure it’s possible. 

I have an updated repo here with better code too:

https://github.com/hallidev/UnityWasapiAudio

Good luck
